# Generated by Django 4.1 on 2023-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncryptedDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("ts", models.DateTimeField()),
                ("doc_id", models.CharField(max_length=255)),
                ("encrypted_doc", models.BinaryField()),
                ("encryption_key", models.BinaryField()),
                ("metadata_uri", models.CharField(max_length=255)),
                ("media_uri", models.CharField(max_length=255)),
                ("tx_hash", models.CharField(max_length=255, null=True)),
                ("network", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
