# Generated by Django 4.1 on 2023-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncryptedDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("doc_id", models.CharField(max_length=255)),
                ("doc_meta", models.BinaryField()),
            ],
        ),
    ]
